
services:
  - type: web
    name: solaris-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python proxy_server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
